const filterArr = [
  {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_1.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_1@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_1.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_1@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_1.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_1@2x.jpg",
    src: "./images/portfolio/portfolio_1.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Технокряк",
    tag: "Веб-сайт",
  },
  {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_2.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_2@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_2.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_2@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_2.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_2@2x.jpg",
    src: "./images/portfolio/portfolio_2.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Постер New Orlean vs Golden Star",
    tag: "Дизайн",
  },
    {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_3.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_3@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_3.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_3@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_3.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_3@2x.jpg",
    src: "./images/portfolio/portfolio_3.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Ресторан Seafood",
    tag: "Приложение",
    },
    {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_4.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_4@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_4.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_4@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_4.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_4@2x.jpg",
    src: "./images/portfolio/portfolio_4.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Проект Prime",
    tag: "Маркетинг",
    },
    {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_5.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_5@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_5.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_5@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_5.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_5@2x.jpg",
    src: "./images/portfolio/portfolio_5.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Проект Boxes",
    tag: "Приложение",
  },
        {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_6.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_6@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_6.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_6@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_6.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_6@2x.jpg",
    src: "./images/portfolio/portfolio_6.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Inspiration has no Borders",
    tag: "Веб-сайт",
  },
  {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_7.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_7@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_7.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_7@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_7.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_7@2x.jpg",
    src: "./images/portfolio/portfolio_7.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Издание Limited Edition",
    tag: "Дизайн",
  },
   {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_8.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_8@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_8.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_8@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_8.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_8@2x.jpg",
    src: "./images/portfolio/portfolio_8.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Проект LAB",
    tag: "Маркетинг",
  },
   {
    mediaDesktop: "(min-width: 1200px)",
    srcsetDesktop1x: "./images/portfolio/desktop_p_9.jpg",
    srcsetDesktop2x: "./images/portfolio/desktop_p_9@2x.jpg",
    mediaTablet: "(min-width: 768px)",
    srcsetTablet1x: "./images/portfolio/tablet_p_9.jpg",
    srcsetTablet2x: "./images/portfolio/tablet_p_9@2x.jpg",
    srcsetMobile1x: "./images/portfolio/portfolio_9.jpg",
    srcsetMobile2x: "./images/portfolio/portfolio_9@2x.jpg",
    src: "./images/portfolio/portfolio_9.jpg",
    alt: "приложение для ресторана",
    text: "Ресурс предлагает комплексные предложения с разным уровнем функционала и сервисов. Все это позволит посетителю получить исчерпывающие сведения <br />о компании или частном лице.",
    heading: "Growing Business",
    tag: "Приложение",
  },
]